### ISSUE TITLE
feat: 자유게시판 테스트 코드 추가

### ISSUE THREAD

**Issue by codefug** [Sprint-Part4-7Team/7team-project#238]
# ✨ feat

## 어떤 작업을 하나요?

-Jest를 활용한 테스트 코드를 추가합니다

**Comment by codefug** [comment]
Cypress가 아직 14버전을 지원하지 않네요 ㅠ

**Comment by ssseeo0** [comment]
오엠지 ~~ 그럼 jest..?!?

**Comment by codefug** [comment]
> 오엠지 ~~ 그럼 jest..?!?

어쩔 수 없이 하나만 해야될듯 하네요
